### ISSUE TITLE
유저 신고 내역 기능 데이터 fetch, 버그 수정

### ISSUE THREAD

**Issue by Bisi3asi** [E-IT-Charge/E-IT-Charge-Api-Server#15]
## Task
 - [ ] feat: 서버 API → 프론트 fetch 기능 화면 구현
 - [ ] fix: 백엔드 로직 버그 수정, 예외 처리
 - [ ] refactor: 프론트 컴포넌트 리팩토링
